name: Update Data from NOAA
on:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
      - name: Update Data
        run: "sh ./scripts/process.sh"
      - name: Commit and Push Data
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions